included:
    - Sources
custom_rules:
  double_space:
    include: "*.swift"
    name: "Double space" 
    regex: "([a-z,A-Z] \s+)" 
    message: "Double space between words" 
    match_kinds: keyword 
    severity: warning 
